<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE sql-jdbc [
  <!ELEMENT jdbc-mapping (driverClass,url,name,password)>
  <!ELEMENT driverClass    (#PCDATA)>
  <!ELEMENT url    		(#PCDATA)>
  <!ELEMENT name 		(#PCDATA)>
  <!ELEMENT password    (#PCDATA)>
]>

<sql-jdbc>
	<jdbc-mapping>
		<driverClass>com.jdbc.mysql.Driver</driverClass>
		<url>jdbc:mysql://127.0.0.1/af_school</url>
		<name>root</name>
	 	<password>aabbcc123</password> 
	</jdbc-mapping>
</sql-jdbc>